/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_menu (void);
GtkWidget* create_GesClient (void);
GtkWidget* create_addClient (void);
GtkWidget* create_delClient (void);
GtkWidget* create_editClient (void);
GtkWidget* create_successDel (void);
GtkWidget* create_alerteDel (void);
GtkWidget* create_SuccessEdit (void);
GtkWidget* create_successAdd (void);
GtkWidget* create_GestionOuv (void);
GtkWidget* create_AddOuv (void);
GtkWidget* create_DeleteOuv (void);
GtkWidget* create_editOuv (void);
GtkWidget* create_fichepres (void);
GtkWidget* create_TauxAbsc (void);
GtkWidget* create_GesPlantation (void);
GtkWidget* create_addPlant (void);
GtkWidget* create_delPlant (void);
GtkWidget* create_editPlant (void);
GtkWidget* create_GesEquipement (void);
GtkWidget* create_addEquipement (void);
GtkWidget* create_editEquipement (void);
GtkWidget* create_delEquipement (void);
GtkWidget* create_gestionCap (void);
GtkWidget* create_AddCap (void);
GtkWidget* create_EditCap (void);
GtkWidget* create_DelCap (void);
GtkWidget* create_bestOuv (void);
GtkWidget* create_addTrou (void);
GtkWidget* create_Gestrou (void);
GtkWidget* create_DelTrou (void);
GtkWidget* create_IntermedEditTrou (void);
GtkWidget* create_editTrou (void);
GtkWidget* create_NumberTrou (void);
GtkWidget* create_typeinf (void);
GtkWidget* create_alerteopp (void);
GtkWidget* create_createAccount (void);
GtkWidget* create_alerteSecurite (void);
GtkWidget* create_capDeff (void);
GtkWidget* create_capAlarmante (void);
GtkWidget* create_windowAnSech (void);
